# Generated by Django 2.2.18 on 2021-06-18 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('AL', 'ALABAMA'), ('AK', 'ALASKA'), ('AZ', 'ARIZONA'), ('AR', 'ARKANSAS'), ('CA', 'CALIFORNIA'), ('CO', 'COLORADO'), ('CT', 'CONNECTICUT'), ('DC', 'DELAWARE'), ('DE', 'FLORIDA'), ('FL', 'GEORGIA'), ('GA', 'HAWAII'), ('HI', 'IDAHO'), ('ID', 'ILLINOIS'), ('IL', 'INDIANA'), ('IN', 'IOWA'), ('IA', 'KANSAS'), ('KS', 'KENTUCKY'), ('KY', 'LOUISIANA'), ('LA', 'MAINE'), ('ME', 'MARYLAND'), ('MD', 'MASSACHUSETTS'), ('MA', 'MICHIGAN'), ('MI', 'MINNESOTA'), ('MN', 'MISSISSIPPI'), ('MS', 'MISSOURI'), ('MO', 'MONTANA'), ('MT', 'NEBRASKA'), ('NE', 'NEVADA'), ('NV', 'NEW HAMPSHIRE'), ('NH', 'NEW JERSEY'), ('NJ', 'NEW MEXICO'), ('NM', 'NEW YORK'), ('NY', 'NORTH CAROLINA'), ('NC', 'NORTH DAKOTA'), ('ND', 'OHIO'), ('OH', 'OKLAHOMA'), ('OK', 'OREGON'), ('OR', 'PENNSYLVANIA'), ('PA', 'RHODE ISLAND'), ('RI', 'SOUTH CAROLINA'), ('SC', 'SOUTH DAKOTA'), ('SD', 'TENNESSEE'), ('TN', 'TEXAS'), ('TX', 'UTAH'), ('UT', 'VERMONT'), ('VT', 'VIRGINIA'), ('VA', 'WASHINGTON'), ('WA', 'WEST VIRGINIA'), ('WV', 'WISCONSIN'), ('WI', 'WYOMING')], max_length=2, null=True)),
                ('country', models.CharField(default='USA', max_length=255)),
            ],
            options={
                'unique_together': {('name', 'city', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('slope', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicap.Course')),
            ],
            options={
                'unique_together': {('course', 'color')},
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('B', 'Both')], max_length=1)),
                ('par1', models.IntegerField()),
                ('si1', models.IntegerField()),
                ('par2', models.IntegerField()),
                ('si2', models.IntegerField()),
                ('par3', models.IntegerField()),
                ('si3', models.IntegerField()),
                ('par4', models.IntegerField()),
                ('si4', models.IntegerField()),
                ('par5', models.IntegerField()),
                ('si5', models.IntegerField()),
                ('par6', models.IntegerField()),
                ('si6', models.IntegerField()),
                ('par7', models.IntegerField()),
                ('si7', models.IntegerField()),
                ('par8', models.IntegerField()),
                ('si8', models.IntegerField()),
                ('par9', models.IntegerField()),
                ('si9', models.IntegerField()),
                ('par10', models.IntegerField()),
                ('si10', models.IntegerField()),
                ('par11', models.IntegerField()),
                ('si11', models.IntegerField()),
                ('par12', models.IntegerField()),
                ('si12', models.IntegerField()),
                ('par13', models.IntegerField()),
                ('si13', models.IntegerField()),
                ('par14', models.IntegerField()),
                ('si14', models.IntegerField()),
                ('par15', models.IntegerField()),
                ('si15', models.IntegerField()),
                ('par16', models.IntegerField()),
                ('si16', models.IntegerField()),
                ('par17', models.IntegerField()),
                ('si17', models.IntegerField()),
                ('par18', models.IntegerField()),
                ('si18', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicap.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('score3', models.IntegerField()),
                ('score4', models.IntegerField()),
                ('score5', models.IntegerField()),
                ('score6', models.IntegerField()),
                ('score7', models.IntegerField()),
                ('score8', models.IntegerField()),
                ('score9', models.IntegerField()),
                ('score10', models.IntegerField()),
                ('score11', models.IntegerField()),
                ('score12', models.IntegerField()),
                ('score13', models.IntegerField()),
                ('score14', models.IntegerField()),
                ('score15', models.IntegerField()),
                ('score16', models.IntegerField()),
                ('score17', models.IntegerField()),
                ('score18', models.IntegerField()),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='handicap.Tee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
