# Generated by Django 2.2.18 on 2021-06-21 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handicap', '0005_auto_20210620_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='course',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='gender',
        ),
        migrations.AddField(
            model_name='round',
            name='course_handicap',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorecard',
            name='par',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorecard',
            name='par_in',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorecard',
            name='par_out',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tee',
            name='scorecard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='handicap.Scorecard'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HandicapHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('handicap', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
