# Generated by Django 2.2.18 on 2021-06-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0006_auto_20210620_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='course_handicap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
