# Generated by Django 2.2.18 on 2021-06-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0010_auto_20210623_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='nh_already_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='nine_holes_combined',
            field=models.BooleanField(default=False),
        ),
    ]
