# Generated by Django 2.2.18 on 2021-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0012_auto_20210623_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='tee',
            name='holes',
            field=models.CharField(choices=[('T', '18'), ('F', 'Front 9'), ('B', 'Back 9')], default='T', max_length=1),
            preserve_default=False,
        ),
    ]
