# Generated by Django 2.2.18 on 2021-06-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handicap', '0013_tee_holes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='nine_holes',
        ),
    ]
