# Generated by Django 2.2.18 on 2021-04-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfpicks',
            name='player5',
            field=models.TextField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfpicks',
            name='player6',
            field=models.TextField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
