# Generated by Django 2.2.18 on 2021-04-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfscore', '0002_auto_20210406_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfpicks',
            name='name',
            field=models.TextField(max_length=64, unique=True),
        ),
    ]
